<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  // 对异步请求进行包装
  // 网络请求: aaa -> 自己处理(10行)
  // 处理: aaa111  -> 自己处理(10行)
  // 处理: aaa111222 -> 自己处理(10行)
  /**
   * 第一种方式
   */
  // new Promise((resolve,reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   },1000)
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res, '第一层10行处理')
  //   // 对结果进行第一次处理
  //   return new Promise((resolve) => {
  //     // resolve(res + '111')
  //     reject('error')
  //   })
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res, '第二层10行处理')
  //   // 对结果进行第二次处理
  //   return new Promise((resolve) => {
  //     resolve(res + '222')
  //   })
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res,'第三层10行处理')
  // })
  /**
   * 第二种方式
   */
  // new Promise((resolve,reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   },1000)
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res,'第一层10行处理')
  //   // 对结果进行第一次处理
  //   return Promise.resolve(res + '111')
  // }).then(res => {
  //     //自己处理10行
  //     console.log(res,'第二层10行处理')
  //     // 对结果进行第二次处理
  //   return Promise.resolve(res + '222')
  // }).then(res => {
  //     //自己处理10行
  //     console.log(res,'第三层10行处理')
  // })
  /**
   * 第三种方式
   *    省略掉Promise.resolve
   */
  // new Promise((resolve,reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   },1000)
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res,'第一层10行处理')
  //   // 对结果进行第一次处理
  //   return res + '111'
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res,'第二层10行处理')
  //   // 对结果进行第二次处理
  //   return res + '222'
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res,'第三层10行处理')
  // })
  /**
   * 出现异常的调用
   */
  // new Promise((resolve,reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   },1000)
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res, '第一层10行处理')
  //   // 对结果进行第一次处理
  //   return new Promise((resolve,reject) => {
  //     // resolve(res + '111')
  //     reject('error')
  //   })
  // }).then(res => {
  //   //自己处理10行
  //   console.log(res, '第二层10行处理')
  //   // 对结果进行第二次处理
  //   return new Promise((resolve) => {
  //     resolve(res + '222')
  //   })
  // }).then(res => {
  //     //自己处理10行
  //     console.log(res,'第三层10行处理')
  // }).catch(error => {
  //   console.log(error)
  // })
  /*
  * 出现异常简写
  * */
  new Promise((resolve,reject) => {
    setTimeout(() => {
      resolve('aaa')
    },1000)
  }).then(res => {
    //自己处理10行
    console.log(res,'第一层10行处理')
    // 对结果进行第一次处理
    return Promise.reject('error')
  }).then(res => {
    //自己处理10行
    console.log(res,'第二层10行处理')
    // 对结果进行第二次处理
    return Promise.resolve(res + '222')
  }).then(res => {
    //自己处理10行
    console.log(res,'第三层10行处理')
  }).catch(err => {
    console.log('error')
  })
</script>
</body>
</html>